import { useMemo, useState } from 'react'
import useSWR from 'swr'
import { FormField, Loader, RenderCards } from '../components'
import type { Post } from '../types'
import { getRandomPrompt } from '../utils'

const fetcher = async (url: string) => await fetch(url).then(async (r) => await r.json())

export default function Home() {
  const [searchText, setSearchText] = useState('')
  const { data, isLoading } = useSWR<{ data: Post[] }>('/api/post', fetcher)

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchText(e.currentTarget.value)
  }

  const posts = useMemo(() => {
    if (searchText === '') return data?.data ?? []

    const filteredPosts = data?.data.filter(({ prompt }) => prompt.toLowerCase().includes(searchText.toLowerCase()))

    return filteredPosts ?? []
  }, [data?.data, searchText])

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-4xl'>The Comunity Showcase </h1>
        <p className='mt-2 text-[#666e75] text-base max-w-lg'>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>

      <div className='mt-16'>
        <FormField labelName='Search posts' type='text' name='text' placeHolder='Search for prompts' value={searchText} onChange={handleSearch} />
      </div>

      <h2 className={`font-medium text-xl mt-6 ${searchText === '' ? 'text-transparent' : 'text-[#666e75]'}`}>
        Showing results form <span className='text-[#222328]'>{searchText}</span>
      </h2>

      <div className='mt-4'>
        {isLoading
          ? (
            <div className='flex justify-center items-center'>
              <Loader />
            </div>
          )
          : (
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              <RenderCards data={posts} title={`${searchText !== '' ? 'No search results found' : 'No posts found'}`} />
            </div>
          )}
      </div>
    </section>
  )
}

